### ISSUE TITLE
Example of registry an indexer

### ISSUE THREAD

**Issue by tmcgroul** [subsquid/subsquid-dao#1]
@mmacedoeu  I haven't found an example of registration. Could you provide it please?
I tried to to call `register` from canvas ui and i got OutOfGas error.
![image](https://user-images.githubusercontent.com/27631177/142198150-f918e39f-2f9c-4b66-a5f0-81dbf800eb6c.png)

Also i did a call from polkadot.js library:
```
async function registerIndexer(api: ApiPromise) {
  const abi = new Abi(reg_metaData, api.registry.getChainProperties());
  const contract = new ContractPromise(api, abi, REGISTRY_ADDRESS);
  const keyring = new Keyring({ type: 'sr25519' });
  const alice = keyring.addFromUri('//Alice');

  const { gasConsumed, result, output } = await contract.query.register(
    alice.address,
    { value: pay_zero, gasLimit },
    'name',
    alice.address,
    1,
    1,
  );
  if (result.isOk) {
    console.log('Success: ', output?.toHuman());
  } else {
    console.log('Error: ', result.asErr.toHuman());
  }
}
```
And i got error: `Error:  { Module: { index: '8', error: '12', message: 'ContractTrapped' } }`

**Comment by tmcgroul** [comment]
I have increased Gas on canvas ui and now both variants have error: ContractTrapped

**Comment by mmacedoeu** [comment]
I need more information, usually this is the workflow: https://github.com/subsquid/subsquid-dao/blob/0385ab56f1b659f825f2e0f624747aa1d1c60bae/nodejs_cli/src/app.ts#L191

1. Make off-chain commitment by calling make_commitment
2. With the commitment hash register the commitment on chain by calling commit (you need to pay fee)
3. Register name on chain by calling register

You can see the test case for register name here: https://github.com/subsquid/subsquid-dao/blob/0385ab56f1b659f825f2e0f624747aa1d1c60bae/contracts/registry/lib.rs#L311

There are some checks to accept the registration so it is better to look into node console to see the ContractTrapped error:

But basically you cannot register without a commit, the commit expires after some N blocks, name should be valid, payment for commit and registration should be enough.

Also make sure the deployment order and passing the epoch_proxy address to the registry instantiation contract, if you the instantiation is incorrect it will always trap any call

**Comment by tmcgroul** [comment]
What i am doing to register an indexer:
1. `docker-compose up`
2. `./build_contract_with_docker.sh`

Then i switch from terminal to browser and instantiate contracts on https://paritytech.github.io/canvas-ui
3. Instantiate epoch contract
![image](https://user-images.githubusercontent.com/27631177/142385604-25178c01-e95b-480d-8112-8619c507f5fd.png)
4. Instantiate epoch-proxy contract
![image](https://user-images.githubusercontent.com/27631177/142387675-552e16ae-ad04-47cc-b92d-fd1eb4d20f57.png)
5. Instantiate registry contract
![image](https://user-images.githubusercontent.com/27631177/142387897-a8651de4-1296-4a4b-ae07-eed0dd06a151.png)
6. Instantiate registry-proxy contract
![image](https://user-images.githubusercontent.com/27631177/142388295-e0a1bfb5-add0-4bb3-9294-8a7e8790c648.png)

Then i call registry contract api:
7. Send rpc-call `make_commitment` and save returned hash
![image](https://user-images.githubusercontent.com/27631177/142389644-d56225d9-3c81-4698-82e9-fef96e102dbb.png)
8. Send transaction `commit` with hash from `make_commitment`
![image](https://user-images.githubusercontent.com/27631177/142390008-8136b1c5-f52e-43b9-bfb2-f59ab14609d9.png)
9. Send transaction `register`
![image](https://user-images.githubusercontent.com/27631177/142390361-d33e91a0-33a6-45b9-b63d-4be358e65e18.png)

After all i get the error:
![image](https://user-images.githubusercontent.com/27631177/142390742-193f8507-a7bd-4891-915e-d2828e9ce073.png)
Where i am wrong?

**Comment by tmcgroul** [comment]
@mmacedoeu i did it, thanks for your help :+1:
