### ISSUE TITLE
Unnecessary argument

### ISSUE THREAD

**Issue by tmcgroul** [subsquid/subsquid-dao#2]
Maybe i am wrong, but what about to remove an argument `from` from [fn register](https://github.com/subsquid/subsquid-dao/blob/main/contracts/registry/lib.rs#L225)?
Can we just take it from `self.env().caller()`?

**Comment by mmacedoeu** [comment]
It enables a third-party to register on your behalf

**Comment by tmcgroul** [comment]
It sounds reasonable
